name: "G3Bot"
version: 1.0
description: "A friendly AI assistant"
news_summary_prompt:
  version: 0.0
  file: 'news_summary_v1.txt'
user_news:
  version: 0.0
  file: 'user_news_v0.txt'
image_prompt_generation_prompt:
  version: 0.0
  file: 'image_prompt_generation_v0.txt'
user_prompt_generation_prompt:
  version: 0.0
  file: 'user_prompt_generation_v0.txt'
headline_generation_prompt:
  version: 0.0
  file: 'headline_generation_v0.txt'
regions: ['Porto Alegre', 'Viam達o']
# regions: ['Porto Alegre', 'Viam達o', 'Alvorada', 'Cachoeirinha', 'S達o Leopoldo', 'Gramado', 'Canela', 'Carlos Barbosa', 'Pelotas', 'S達o Jorge']